version: "3.8"
services:
  prometheus:
    image: prom/prometheus:v2.23.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-2.23.0.linux-amd64:/etc/prometheus:z
      - ./prometheus-2.23.0.linux-amd64:/prometheus:z
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - infracloudio
  infracloudio:
    image: infracloudio/csvserver:latest
    container_name: infracloudio
    ports:
      - "9393:9300"
    volumes:
      - ./csvserver/inputFile:/csvserver/inputdata